# -*- coding: utf-8 -*-
"""585 naascom case study 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-86kNL6JoxhF6kZkCgJRR2Hty5ociaFh
"""

battery_data = [
    [0, 32, 400, 20, 95],
    [1, 35, 395, 22, 88],
    [2, 38, 390, 25, 80],
    [3, 40, 385, 28, 70],
    [4, 42, 380, 30, 60],
    [5, 45, 375, 32, 48]
]

battery_data = [
    [0, 32, 400, 20, 95],
    [1, 35, 395, 22, 88],
    [2, 38, 390, 25, 80],
    [3, 40, 385, 28, 70],
    [4, 42, 380, 30, 60],
    [5, 45, 375, 32, 48]
]

for data in battery_data:
    print("Time:", data[0], "h")
    print("Temperature:", data[1], "°C")
    print("Voltage:", data[2], "V")
    print("Current:", data[3], "A")
    print("Charge:", data[4], "%")
    print("----------------------")

for data in battery_data:
    temperature = data[1]

    if temperature > 40:
        print("High Temperature:", temperature, "°C")

for data in battery_data:
    print(data)

for data in battery_data:
    temperature = data[1]

    if temperature > 40:
        print("High Temperature Alert")
    else:
        print("Temperature Normal")

for data in battery_data:
    charge = data[4]

    if charge < 50:
        print("Low Battery Alert")
    else:
        print("Battery Charge Normal")

def battery_status(charge):
    if charge > 70:
        return "High"
    elif charge >= 50:
        return "Medium"
    else:
        return "Low"

print(battery_status(95))
print(battery_status(70))
print(battery_status(48))

import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

T_avg = np.mean(D[:, 0])
print("Average Temperature:", T_avg)

V_avg = np.mean(D[:, 1])
print("Average Voltage:", V_avg)

I_avg = np.mean(D[:, 2])
print("Average Current:", I_avg)

C_avg = np.mean(D[:, 3])
print("Average Charge:", C_avg)

T_max = np.max(D[:, 0])
T_min = np.min(D[:, 0])

print("Maximum Temperature:", T_max)
print("Minimum Temperature:", T_min)

high_temp = D[D[:, 0] > 40]

print(high_temp)

low_battery = D[D[:, 3] < 50]

print(low_battery)

import numpy as np

A = np.array([
    [2, 1],
    [1, 3]
])

X = np.array([
    [40],
    [25]
])

Y = A @ X

print("Y =")
print(Y)

A_transpose = A.T

print(A_transpose)

det_A = np.linalg.det(A)

print("Determinant:", det_A)

A_inverse = np.linalg.inv(A)

print("Inverse of A:")
print(A_inverse)

import numpy as np

A = np.array([
    [2, 1],
    [1, 3]
])

B = np.array([
    100,
    120
])

X = np.linalg.solve(A, B)

print("x =", X[0])
print("y =", X[1])

import sympy as sp

t = sp.symbols('t')

C = 100 - 2*t - (1/2)*t**2

dC_dt = sp.diff(C, t)

print("dC/dt =", dC_dt)

rate = -2 - t

rate_at_2 = rate.subs(t, 2)
rate_at_5 = rate.subs(t, 5)

print("Rate at t = 2:", rate_at_2)
print("Rate at t = 5:", rate_at_5)

rate_at_2 = dC_dt.subs(t, 2)
rate_at_5 = dC_dt.subs(t, 5)

print("dC/dt at t = 2:", rate_at_2)
print("dC/dt at t = 5:", rate_at_5)

import numpy as np

D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

print("Average Temperature:", np.mean(D[:, 0]))
print("Average Voltage:", np.mean(D[:, 1]))
print("Average Current:", np.mean(D[:, 2]))
print("Average Charge:", np.mean(D[:, 3]))

import sympy as sp

t = sp.symbols('t')

C = 100 - 2*t - (1/2)*t**2

dC_dt = sp.diff(C, t)

print("dC/dt =", dC_dt)

import numpy as np

A = np.array([
    [2, 1],
    [1, 3]
])

X = np.array([
    [40],
    [25]
])

Y = A @ X

print("Y =")
print(Y)

B = np.array([100, 120])

solution = np.linalg.solve(A, B)

print("x =", solution[0])
print("y =", solution[1])